if(NOT DEFINED DJAPP_SOURCE_DIR)
    message(FATAL_ERROR "DJAPP_SOURCE_DIR is required")
endif()
if(NOT DEFINED DJAPP_BINARY_DIR)
    message(FATAL_ERROR "DJAPP_BINARY_DIR is required")
endif()
if(NOT DEFINED DJAPP_LICENSE_REPORT)
    set(DJAPP_LICENSE_REPORT "${DJAPP_BINARY_DIR}/license-report.spdx.txt")
endif()

file(MAKE_DIRECTORY "${DJAPP_BINARY_DIR}")
set(report "")
string(APPEND report "SPDXVersion: SPDX-2.3\n")
string(APPEND report "DataLicense: CC0-1.0\n")
string(APPEND report "SPDXID: SPDXRef-DOCUMENT\n")
string(APPEND report "DocumentName: DJApp alpha dependency license inventory\n")
string(APPEND report "DocumentNamespace: https://example.invalid/djapp/alpha/license-inventory\n")
string(APPEND report "Creator: Tool: CMake license-report target\n")
string(TIMESTAMP now "%Y-%m-%dT%H:%M:%SZ" UTC)
string(APPEND report "Created: ${now}\n\n")

string(APPEND report "PackageName: DJApp project source\n")
string(APPEND report "SPDXID: SPDXRef-Package-DJApp\n")
string(APPEND report "PackageDownloadLocation: NOASSERTION\n")
string(APPEND report "FilesAnalyzed: false\n")
string(APPEND report "PackageLicenseDeclared: NOASSERTION\n")
string(APPEND report "PackageLicenseConcluded: NOASSERTION\n")
string(APPEND report "PackageComment: Project source license must be finalized before distribution; no telemetry, crash upload, accounts, cloud sync, marketplace, or remote logging infrastructure is present in alpha.\n\n")

string(APPEND report "PackageName: JUCE framework\n")
string(APPEND report "SPDXID: SPDXRef-Package-JUCE\n")
string(APPEND report "PackageDownloadLocation: NOASSERTION\n")
string(APPEND report "FilesAnalyzed: false\n")
string(APPEND report "PackageLicenseDeclared: LicenseRef-JUCE-Commercial OR GPL-3.0-or-later\n")
string(APPEND report "PackageLicenseConcluded: NOASSERTION\n")
string(APPEND report "PackageComment: Release gate before distribution: choose and document either a valid JUCE commercial license or GPL-compatible distribution posture. JUCE is not vendored here; CMake uses find_package(JUCE CONFIG) or an explicitly licensed third_party/JUCE checkout when supplied.\n\n")

string(APPEND report "PackageName: SQLite system C API target\n")
string(APPEND report "SPDXID: SPDXRef-Package-SQLite-System-C-API\n")
string(APPEND report "PackageDownloadLocation: NOASSERTION\n")
string(APPEND report "FilesAnalyzed: false\n")
string(APPEND report "PackageLicenseDeclared: blessing\n")
string(APPEND report "PackageLicenseConcluded: blessing\n")
string(APPEND report "PackageComment: Commercial-compatible target is the operating-system/system SQLite C API. This local bootstrap build uses the explicit in-memory alpha backend when linkable system SQLite is unavailable; no SQLite wrapper or vendored DB dependency is added.\n\n")

string(APPEND report "PackageName: Vendored third-party dependencies\n")
string(APPEND report "SPDXID: SPDXRef-Package-No-Vendored-Third-Party\n")
string(APPEND report "PackageDownloadLocation: NONE\n")
string(APPEND report "FilesAnalyzed: false\n")
string(APPEND report "PackageLicenseDeclared: NOASSERTION\n")
string(APPEND report "PackageLicenseConcluded: NOASSERTION\n")
string(APPEND report "PackageComment: Current posture is no vendored third-party dependency checkout in source control. Optional third_party/JUCE is allowed only as a local licensed checkout and remains a release-license gate.\n")

file(WRITE "${DJAPP_LICENSE_REPORT}" "${report}")
message(STATUS "Wrote ${DJAPP_LICENSE_REPORT}")
