if(NOT DEFINED DJAPP_SOURCE_DIR)
    message(FATAL_ERROR "DJAPP_SOURCE_DIR is required")
endif()
if(NOT DEFINED DJAPP_BINARY_DIR)
    message(FATAL_ERROR "DJAPP_BINARY_DIR is required")
endif()
if(NOT DEFINED DJAPP_LICENSE_REPORT)
    set(DJAPP_LICENSE_REPORT "${DJAPP_BINARY_DIR}/license-report.spdx.txt")
endif()

file(MAKE_DIRECTORY "${DJAPP_BINARY_DIR}")
set(report "")
string(APPEND report "SPDXVersion: SPDX-2.3\n")
string(APPEND report "DataLicense: CC0-1.0\n")
string(APPEND report "SPDXID: SPDXRef-DOCUMENT\n")
string(APPEND report "DocumentName: DJApp dependency license inventory\n")
string(APPEND report "DocumentNamespace: https://example.invalid/djapp/license-inventory\n")
string(APPEND report "Creator: Tool: CMake license-report target\n")
string(TIMESTAMP now "%Y-%m-%dT%H:%M:%SZ" UTC)
string(APPEND report "Created: ${now}\n\n")

string(APPEND report "PackageName: DJApp project source\n")
string(APPEND report "SPDXID: SPDXRef-Package-DJApp\n")
string(APPEND report "PackageDownloadLocation: NOASSERTION\n")
string(APPEND report "FilesAnalyzed: false\n")
string(APPEND report "PackageLicenseDeclared: AGPL-3.0-or-later\n")
string(APPEND report "PackageLicenseConcluded: AGPL-3.0-or-later\n")
string(APPEND report "PackageComment: Repository source is governed by LICENSE as GNU Affero General Public License version 3 or later. This inventory is an engineering compliance aid, not legal advice.\n\n")

string(APPEND report "PackageName: JUCE framework\n")
string(APPEND report "SPDXID: SPDXRef-Package-JUCE\n")
string(APPEND report "PackageDownloadLocation: https://github.com/juce-framework/JUCE\n")
string(APPEND report "FilesAnalyzed: false\n")
string(APPEND report "PackageLicenseDeclared: AGPL-3.0-only OR LicenseRef-JUCE-Commercial\n")
string(APPEND report "PackageLicenseConcluded: AGPL-3.0-only OR LicenseRef-JUCE-Commercial\n")
string(APPEND report "PackageComment: Planned native app dependency. This project uses the AGPL-compatible JUCE open-source path with project AGPL-3.0-or-later posture unless a separate valid JUCE commercial license is documented. JUCE is not vendored here; CMake uses find_package(JUCE CONFIG), CMAKE_PREFIX_PATH, or an explicitly licensed local third_party/JUCE checkout when supplied.\n\n")

string(APPEND report "PackageName: Steinberg VST3 SDK\n")
string(APPEND report "SPDXID: SPDXRef-Package-VST3-SDK\n")
string(APPEND report "PackageDownloadLocation: https://github.com/steinbergmedia/vst3sdk\n")
string(APPEND report "FilesAnalyzed: false\n")
string(APPEND report "PackageLicenseDeclared: MIT\n")
string(APPEND report "PackageLicenseConcluded: MIT\n")
string(APPEND report "PackageComment: Planned plugin hosting SDK dependency for VST3 processing and editor windows. Do not vendor in this task; add only through reviewed dependency integration.\n\n")

string(APPEND report "PackageName: Rubber Band Library\n")
string(APPEND report "SPDXID: SPDXRef-Package-RubberBand\n")
string(APPEND report "PackageDownloadLocation: https://breakfastquay.com/rubberband/\n")
string(APPEND report "FilesAnalyzed: false\n")
string(APPEND report "PackageLicenseDeclared: GPL-2.0-or-later\n")
string(APPEND report "PackageLicenseConcluded: GPL-2.0-or-later\n")
string(APPEND report "PackageComment: Optional system primary time-stretch and pitch-lock engine. CMake links Rubber Band only when a reviewed system install is available; live playback must use OptionProcessRealTime, while R3/high-quality offline modes are reserved for non-callback processing. GPL-2.0-or-later remains aligned with the project AGPL-3.0-or-later posture through the GPLv3-or-later upgrade path.\n\n")

string(APPEND report "PackageName: Signalsmith Stretch\n")
string(APPEND report "SPDXID: SPDXRef-Package-Signalsmith-Stretch\n")
string(APPEND report "PackageDownloadLocation: https://github.com/Signalsmith-Audio/signalsmith-stretch\n")
string(APPEND report "FilesAnalyzed: false\n")
string(APPEND report "PackageLicenseDeclared: MIT\n")
string(APPEND report "PackageLicenseConcluded: MIT\n")
string(APPEND report "PackageComment: Signalsmith-compatible fallback adapter boundary for no-Rubber-Band builds. No Signalsmith source is vendored here; production integration still requires reviewed dependency intake.\n\n")

string(APPEND report "PackageName: SoundTouch\n")
string(APPEND report "SPDXID: SPDXRef-Package-SoundTouch\n")
string(APPEND report "PackageDownloadLocation: https://www.surina.net/soundtouch/\n")
string(APPEND report "FilesAnalyzed: false\n")
string(APPEND report "PackageLicenseDeclared: LGPL-2.1-only\n")
string(APPEND report "PackageLicenseConcluded: LGPL-2.1-only\n")
string(APPEND report "PackageComment: Legacy fallback option only. Any future integration must preserve LGPL obligations and remain subordinate to Rubber Band primary.\n\n")

string(APPEND report "PackageName: SQLite system C API target\n")
string(APPEND report "SPDXID: SPDXRef-Package-SQLite-System-C-API\n")
string(APPEND report "PackageDownloadLocation: NOASSERTION\n")
string(APPEND report "FilesAnalyzed: false\n")
string(APPEND report "PackageLicenseDeclared: blessing\n")
string(APPEND report "PackageLicenseConcluded: blessing\n")
string(APPEND report "PackageComment: Planned persistence dependency is the operating-system/system SQLite C API. This local bootstrap build may use the explicit in-memory alpha backend when linkable system SQLite is unavailable; no SQLite wrapper or vendored DB dependency is added.\n\n")

string(APPEND report "PackageName: Vendored third-party dependencies\n")
string(APPEND report "SPDXID: SPDXRef-Package-No-Vendored-Third-Party\n")
string(APPEND report "PackageDownloadLocation: NONE\n")
string(APPEND report "FilesAnalyzed: false\n")
string(APPEND report "PackageLicenseDeclared: NOASSERTION\n")
string(APPEND report "PackageLicenseConcluded: NOASSERTION\n")
string(APPEND report "PackageComment: Current posture is no vendored JUCE, VST3 SDK, Rubber Band, Signalsmith, SoundTouch, SQLite wrapper, or other third-party dependency checkout in source control. Optional third_party/JUCE is allowed only as a local licensed checkout and remains a license gate.\n")

file(WRITE "${DJAPP_LICENSE_REPORT}" "${report}")
message(STATUS "Wrote ${DJAPP_LICENSE_REPORT}")
